name: Production of FAANG Report
run-name: ${{ github.actor }} is creating FAANG Report
on: 
  schedule:
  - cron: '0 11 * * 6'  # At 11:00 AM every Saturday
  workflow_dispatch:
permissions: write-all
jobs:
  Create_FAANG_Report:
    name: Create FAANG Report
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: |
          echo "Starting FAANG Report Generation"
      - run: |
          ls -a $GITHUB_WORKSPACE
      - name: FAANG Report Generation
        run: |
          ${GITHUB_WORKSPACE}/faang.py
      - run: |
          echo "FAANG Report Generated Successfully"
      - name: "Commit and Push Changes"
        run: |
          git add .
          git commit -m "Automated FAANG Report Update"
          git push origin HEAD:main
      - run: |
          echo "FAANG Report Changes Pushed Successfully"
